### ISSUE TITLE
getMethods gives null pointer

### ISSUE THREAD

**Issue by svenstm** [almende/eve#15]
When opening the webinterface of an agent. I get the following error:

sep 27, 2013 1:50:21 PM com.almende.eve.rpc.jsonrpc.JSONRPC _describe
WARNING: Failed to describe class
java.lang.NullPointerException
    at com.almende.eve.rpc.jsonrpc.JSONRPC._describe(JSONRPC.java:231)
    at com.almende.eve.rpc.jsonrpc.JSONRPC._describe(JSONRPC.java:265)
    at com.almende.eve.rpc.jsonrpc.JSONRPC.describe(JSONRPC.java:291)
    at com.almende.eve.agent.AgentHost.getMethods(AgentHost.java:741)
    at com.almende.eve.agent.Agent.getMethods(Agent.java:266)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

It doesn't matter if I use the JSONFileStateFactory.

**Comment by svenstm** [comment]
Ok already found the cause. The Scheduler in eve.yaml was still set to:

scheduler:
  class: RunnableScheduler

Which in version 2.0.0 gives a warning for deprecation. But in 2.1.0-SNAPSHOT the warning is gone and will simply fail. But also causes this issue.

**Comment by ludost** [comment]
Will commit a fix later, adding some extra resilience against missing Namespace providers. (In this case the getScheduler file for the "scheduler" namespace returned null.)
